### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by devxprite**
Hey @0xJin ,

I added some new badges and try to make it better by making some changes in the old README file.

### CODE REVIEW

**Comment by 0xJin** [comment]
Thank you , i 'll approved this requests :)

**Review by 0xJin — APPROVED** [review]

**Review by 0xJin — COMMENTED** [review]
we can do that

**Comment by krishpranav** [comment]
so previous pull request I have added rust scan can you add about it on the README.md??

**Comment by 0xJin** [comment]
Update it now :) @7ORP3DO

**Comment by 7ORP3DO** [comment]
Thanks @0xJin.

**Pull request merged**
